[theme]

backgroundColor ="#C8E6C9"#change the main app background
secondaryBackgroundColor ="#E0E0E0" # Changes sidebar and widget backgrounds

textColor = "#000000" # Changes main text color

primaryColor = "#F5E7DE" # Changes primary accent color


