[theme]

backgroundColor = "#D3D3D3"#change the main app background
secondaryBackgroundColor ="#D2B48C" # Changes sidebar and widget backgrounds

textColor = "#000000" # Changes main text color

primaryColor = "#F5E7DE" # Changes primary accent color


